#spring.application.name=shopping
server:
  port: 8081
  servlet:
    context-path: "/shopping"
spring:
  application:
    name: shopping
  datasource:
    url: 'jdbc:mysql://localhost:3306/shopping'
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "8tT3Q7fEC1EzBFHyIY43ihghzzA/6M5H0XZ3NLcgXbgo+Cgvs0rCa5KIz5BMAZ0O"
